### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by LinArcX** [wangyi2005/ng-hr#1]
Hi. i deploy __ng-hr__ to __heroku__. but i don't know how to use it as a normal vpn.
I have to bypass government censorship to access some sites. but i haven't no glue to do it right.

**Comment by wangyi2005** [comment]
v2ray client config.json
vmess:  "address": "####.herokuapp.com","port": 443, "id": **UUID**
"streamSettings":  "network": "ws", "security": "tls"
"wsSettings":  "path": **PATH**

**Comment by LinArcX** [comment]
In linux i [use v2ray package and call it with passing a config file](https://v2ray.com/en/welcome/start.html), but i get an error:

```
╰ v2ray --config=/etc/v2ray/config.json
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory

 > exit status 255
```

**Comment by wangyi2005** [comment]
geoip.dat ？

**Comment by LinArcX** [comment]
Oh, sorry. it's a bug related to arch package:
https://bugs.archlinux.org/task/60943?project=0&order=id&sort=desc&string=v2ray

**Comment by wangyi2005** [comment]
"address": "myguesty.herokuapp.com"

**Comment by LinArcX** [comment]
It looks like better:
https://gist.github.com/LinArcX/3146de3214e1ebcf2f0d9c94b083eaff

**Comment by wangyi2005** [comment]
and
"streamSettings": {
     "network": "ws",
     "security": "tls"
    }

**Comment by LinArcX** [comment]
Where add them?

**Comment by wangyi2005** [comment]
replace ### with  vars 
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "#########",
            "port": 443,
            "users": [
              {
                "id": "#################",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/#####"
        }
      }
    }
  ]
}

**Comment by LinArcX** [comment]
Yesss. awesome. thank you so much.
